medallion:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_SILVER') }}"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: "{{ env_var('GCP_CREDENTIALS_PATH') }}"
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DATASET_SILVER') }}"
      threads: 8
      timeout_seconds: 600
      location: US
      priority: interactive
      keyfile: "{{ env_var('GCP_CREDENTIALS_PATH') }}"
