name: dbt CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'silver/transformations/**'
      - 'gold/final/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'silver/transformations/**'
      - 'gold/final/**'

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      BIGQUERY_DATASET_SILVER: ${{ secrets.BIGQUERY_DATASET_SILVER }}
      BIGQUERY_DATASET_GOLD: ${{ secrets.BIGQUERY_DATASET_GOLD }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-bigquery pytest python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Run dbt tests
      run: |
        cd silver/transformations
        dbt deps
        dbt compile --profiles-dir ./profiles
        dbt test --profiles-dir ./profiles
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        BIGQUERY_DATASET_SILVER: ${{ secrets.BIGQUERY_DATASET_SILVER }}
        BIGQUERY_DATASET_GOLD: ${{ secrets.BIGQUERY_DATASET_GOLD }}
    
    - name: Run pytest
      run: |
        cd tests
        pytest unit_tests/
    
  dbt-deploy:
    needs: dbt-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger dbt Cloud Job
      uses: dbt-labs/dbt-cloud-action@v1
      with:
        dbt_cloud_token: ${{ secrets.DBT_CLOUD_TOKEN }}
        dbt_cloud_account_id: ${{ secrets.DBT_CLOUD_ACCOUNT_ID }}
        dbt_cloud_job_id: ${{ secrets.DBT_CLOUD_JOB_ID }}
        wait_for_job_completion: true
        timeout_seconds: 3600 